### ISSUE TITLE
About 81 aggregated keypoints

### ISSUE THREAD

**Issue by deepkyu** [lzhbrian/deepfashion2-kps-agg-finetune#2]
First of all, congrats for 1st place in DeepFashion2 competition! 🥇 
It is very impressive for me and I'm trying to follow up your method for finding keypoints in the dataset.
Is there any .json file with aggregated keypoints or a method for making aggregated keypoint label file?

**Comment by deepkyu** [comment]
I found it. Thanks a lot and congrats again!!

**Comment by ktro2828** [comment]
@deepkyu hi! I'm confusing where I can find .json files, can you help me ??

**Comment by Mamba-ZJP** [comment]
Could you tell me where to find the .json file of person detection result, please?
